[package]
name = "package_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.6"
tokio = "1"
ar = "0.9.0"
tar = "0.4.37"
xz = "0.1.0"