name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
      env:
        RUSTC_FLAGS: -C target-cpu=native

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Setup
        run: sudo target/release/opm
      - name: Run tests
        run: cargo test --verbose --release
